version: '3.8'

services:
  backend:
    build:
      context: ./HahnCargoSim   # Path to the BackEnd directory
    ports:
      - "5000:80"  # Adjust the port if necessary

  frontend:
    build:
      context: ./hahn-cargo-simulation   # Path to the FrontEnd directory
    ports:
      - "3000:80"  # Adjust the port if necessary
    develop:
      watch:
        - path: ./hahn-cargo-simulation/package.json
          action: rebuild
        - path: ./hahn-cargo-simulation
          target: /usr/src/app
          action: sync
    environment:
      - CHOKIDAR_USEPOLLING=true

  consumer:
    build:
      context: ./hahn-cargo-simulation/consumer  # Ajusta la ruta al directorio del consumidor
    ports:
      - "9081:9081"
    depends_on:
      - rabbitmq
    restart: always
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"